# This is the main.yml playbook file for installing the following solftware below

#httpd
  - name: Install httpd
    dnf:
      name:
        - httpd
        - php
      state: latest

  - name: Configure httpd
    service:
      name: httpd
      state: restarted

#Nagios
  - name: nagios libraries
    tags: libraries, dependencies
    package:
      name:
        - gcc
        - glibc
        - glibc-common
        - perl
        - httpd
        - php
        - wget
        - gd
        - gd-devel
        - openssl-devel
        - make
        - gettext
        - automake
        - net-snmp
        - net-snmp-utils
        - python3-pip
        - python3

  - name: passlib package
    pip:
      name: passlib

  - name: Nagios directory PATH
    file:
      path: ~/nagios
      state: directory

  - name: downloading nagios
    unarchive:
      src: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
      dest: ~/nagios
      remote_src: yes
      mode: 0777
      owner: root
      group: root

  - name: downloading nagios plugins
    unarchive:
      src: https://github.com/nagios-plugins/nagios-plugins/archive/release-2.3.3.tar.gz
      dest: ~/nagios
      remote_src: yes
      mode: 0777
      owner: root
      group: root

  - name: install, compile, adding users and groups
    shell: |
     cd ~/nagios/nagioscore-**
     ./configure
     make install-groups-users
     usermod -a -G nagios apache
     name install
     make install-daemoninit
     make install-commandmode
     make install-config
     make install-webconf
  - name: compile and install plugins
    shell: |
      cd ~/nagios/nagios-plugins*
      ./tools/setup
      ./configure
      make
      make install
  - name: Adding Users to nagios
    community.general.htpasswd:
      path: /usr/local/nagios/etc/htpasswd.users
      name: admin
      password: admin


  - name: Nagios Start/Enable Check
    service:
      name: nagios
      state: restarted
      enabled: true

  - name: Apache/httpd Start/Enable Check
    service:
      name: httpd
      state: restarted
      enabled: true
